version: "3"
services:
 ms-sql-server:
  image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  environment:
   ACCEPT_EULA: "Y"
   MSSQL_SA_PASSWORD: "Pa55w0rd2021"
   MSSQL_PID: "Express"
  ports:
   - "1433:1433"

 dev-app:
  image: node:alpine
  container_name: dev-app
  restart: always
  working_dir: /usr/src/app
  ports:
   - "3001:3001"
  command: [sh, -c, "npm run dev"]
  volumes:
   - "../:/usr/src/app/"
   - "../src/:/usr/src/app/src/"
   - "../node_modules/:/usr/src/app/node_modules/"
  tty: true
  environment:
   HOST: 0.0.0.0
   PORT: 3001
   NUXT_PUBLIC_API_BASE: "https://localhost:6001/api/"
